version: 0.2

# env:
#   variables:
#     # ASGs
#     GREEN_MAIN_ASG: "main-green-asg"
#     GREEN_FACULTY_ASG: "faculty-green-asg"
#     BLUE_MAIN_ASG: "main-blue-asg"
#     BLUE_FACULTY_ASG: "faculty-blue-asg"

#     # ALB rules
#     MAIN_RULE_ARN: ""
#     FACULTY_RULE_ARN: ""

#     # Target groups
#     MAIN_GREEN_TG: ""
#     FACULTY_GREEN_TG: ""

phases:
  pre_build:
    commands:
      - aws --version
      - echo "Starting Blue/Green deployment..."
      - echo "GREEN_MAIN_ASG=$GREEN_MAIN_ASG"
      - echo "BLUE_MAIN_ASG=$BLUE_MAIN_ASG"
      - echo "GREEN_FACULTY_ASG=$GREEN_FACULTY_ASG"
      - echo "BLUE_FACULTY_ASG=$BLUE_FACULTY_ASG"
      - |
        if [ -z "$GREEN_MAIN_ASG" ] || [ -z "$BLUE_MAIN_ASG" ]; then
          echo "ERROR: ASG names not set!"
          exit 1
        fi

  build:
    commands:
      - echo "Scaling up GREEN ASGs..."
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name $GREEN_MAIN_ASG --desired-capacity 1
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name $GREEN_FACULTY_ASG --desired-capacity 1

      - echo "Waiting for GREEN ASGs to be in service..."
      # - aws autoscaling wait group-in-service --auto-scaling-group-names $GREEN_MAIN_ASG
      # - aws autoscaling wait group-in-service --auto-scaling-group-names $GREEN_FACULTY_ASG
      - |
        echo "Waiting for GREEN MAIN ASG instances to be InService..."
        while true; do
          COUNT=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$GREEN_MAIN_ASG" \
            --query "AutoScalingGroups[0].Instances[?LifecycleState=='InService' && HealthStatus=='Healthy'] | length(@)" \
            --output text)
          if [ "$COUNT" -ge 1 ]; then
            echo "GREEN MAIN ASG ready"
            break
          fi
          echo "Waiting..."
          sleep 20
        done

      - |
        echo "Waiting for GREEN FACULTY ASG instances to be InService..."
        while true; do
          COUNT=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$GREEN_FACULTY_ASG" \
            --query "AutoScalingGroups[0].Instances[?LifecycleState=='InService' && HealthStatus=='Healthy'] | length(@)" \
            --output text)
          if [ "$COUNT" -ge 1 ]; then
            echo "GREEN FACULTY ASG ready"
            break
          fi
          echo "Waiting..."
          sleep 20
        done



      - echo "Switching ALB rules to GREEN target groups..."
      - aws elbv2 modify-rule --rule-arn $MAIN_RULE_ARN --actions Type=forward,TargetGroupArn=$MAIN_GREEN_TG
      - aws elbv2 modify-rule --rule-arn $FACULTY_RULE_ARN --actions Type=forward,TargetGroupArn=$FACULTY_GREEN_TG

      # - echo "Scaling down BLUE ASGs..."
      # - aws autoscaling update-auto-scaling-group --auto-scaling-group-name $BLUE_MAIN_ASG --desired-capacity 0
      # - aws autoscaling update-auto-scaling-group --auto-scaling-group-name $BLUE_FACULTY_ASG --desired-capacity 0

      - echo "Lowering BLUE ASG min size..."
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name $BLUE_MAIN_ASG --min-size 0
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name $BLUE_FACULTY_ASG --min-size 0

      - echo "Scaling down BLUE ASGs..."
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name $BLUE_MAIN_ASG --desired-capacity 0
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name $BLUE_FACULTY_ASG --desired-capacity 0

  post_build:
    commands:
      - echo "Blue/Green deployment completed successfully."
