# Base image with PHP 8.3 + CLI + extensions
FROM php:8.3-cli

# Set working directory
WORKDIR /var/www/html

# Install system dependencies
# RUN apt-get update && apt-get install -y \
#     git \
#     unzip \
#     libzip-dev \
#     libonig-dev \
#     curl \
#     libcurl4-openssl-dev \
#     libssl-dev \
#     libsqlite3-dev \
#     pkg-config \
#     libbrotli-dev \
#     && docker-php-ext-install pdo_mysql mbstring zip curl sockets


RUN apt-get update && apt-get install -y \
    git unzip libzip-dev libonig-dev curl libcurl4-openssl-dev libssl-dev \
 && docker-php-ext-install pcntl \
 && pecl install redis swoole \
 && docker-php-ext-enable redis swoole


# Install Redis PHP extension
RUN pecl install redis && docker-php-ext-enable redis

# Install Swoole PHP extension
RUN pecl install swoole && docker-php-ext-enable swoole

# Install Composer
COPY --from=composer:2.8 /usr/bin/composer /usr/bin/composer

# Copy project files
COPY . .

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Expose port 8000 for Octane
EXPOSE 8000

# Command to run Octane
CMD ["php", "artisan", "octane:start", "--server=swoole", "--host=0.0.0.0", "--port=8000"]
